In [ ]:
# ワインのデータをK-meansで３つにクラスタリングする
#https://datahexa.com/kmeans-clustering-with-wine-dataset/参考

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import cluster, preprocessing, datasets

from sklearn.cluster import KMeans

In [2]:
wine = datasets.load_wine()


In [3]:
X = wine.data
print(X)

[[1.423e+01 1.710e+00 2.430e+00 ... 1.040e+00 3.920e+00 1.065e+03]
 [1.320e+01 1.780e+00 2.140e+00 ... 1.050e+00 3.400e+00 1.050e+03]
 [1.316e+01 2.360e+00 2.670e+00 ... 1.030e+00 3.170e+00 1.185e+03]
 ...
 [1.327e+01 4.280e+00 2.260e+00 ... 5.900e-01 1.560e+00 8.350e+02]
 [1.317e+01 2.590e+00 2.370e+00 ... 6.000e-01 1.620e+00 8.400e+02]
 [1.413e+01 4.100e+00 2.740e+00 ... 6.100e-01 1.600e+00 5.600e+02]]


In [4]:
X.shape

(178, 13)

In [5]:
y=wine.target
print(y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]


In [6]:
y.shape

(178,)

In [7]:
# ワインのターゲット名は、'class_0', 'class_1', 'class_2'　の3種類
wine.target_names

array(['class_0', 'class_1', 'class_2'], dtype='<U7')

In [8]:
model = KMeans(n_clusters=3)

In [9]:
labels = model.fit_predict(X)

In [10]:
df = pd.DataFrame({'labels': labels})
type(df)

pandas.core.frame.DataFrame

In [11]:
def species_label(theta):
    if theta == 0:
        return wine.target_names[0]     # 'class_0'
    if theta == 1:
        return wine.target_names[1]     # 'class_1'
    if theta == 2:
        return wine.target_names[2]     # 'class_2'

In [12]:
df['species'] = [species_label(theta) for theta in wine.target]

In [13]:
# pd.crosstab()：クロス集計　第一引数indexに結果の行見出しとなる列、第二引数columnsに結果の列見出しとなる列を指定
pd.crosstab(df['labels'], df['species'])

species  class_0  class_1  class_2
labels                            
0             46        1        0
1              0       50       19
2             13       20       29

k-means（k=3）のクラスタリングの結果、グループlabels 0はclass_1（50/69）が最大で、

グループlabels 1はclass_0（46/47）が最大。ただし、グループlabels 2はclass_2（29/62）

が多いが他のclassも多く混じっていて、labels 2は上手くクラスタリングできていない。